module.exports = {
	'gmail.com': 'mail.google.com',
	'sina.com': 'mail.sina.com.cn',
	'sina.com.cn': 'mail.sina.com.cn',
	'vip.sina.com': 'mail.sina.com.cn',
	'163.com': 'mail.163.com',
	'188.com': 'mail.188.com',
	'126.com': 'mail.126.com',
	'yeah.net': 'mail.yeah.net',
	'sohu.com': 'mail.sohu.com',
	'qq.com': 'mail.qq.com',
	'vip.qq.com': 'mail.qq.com',
	'foxmail.com': 'mail.qq.com',
	'hotmail.com': 'www.hotmail.com',
	'msn.com': 'www.live.com',
	'live.com': 'www.live.com',
	'live.cn': 'www.live.cn',
	'yahoo.cn': 'mail.cn.yahoo.com',
	'yahoo.com.cn': 'mail.cn.yahoo.com',
	'yahoo.com': 'mail.yahoo.com',
	'21cn.com': 'mail.21cn.com',
	'tom.com': 'mail.tom.com',
	'vip.tom.com': 'vip.tom.com',
	'163.net': 'vip.tom.com',
}
